# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTRhYjhjZWY2N2FkN2I1NWEyYzEwNDU1MzhlN2E1NGE4NzJjNGZjMDY3NjIxMTlkN2VhOWY4NmMzYjI0MWZjZDk5NmVmMTFmMzZhMDk4ODRmODFhMzIzZmYxOGM4Nzg4NzcyNWRmMmI5YWE0MjJjNGQ2NmViYTgxOTI5ZDE1NTg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
